services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  take_home_server:
    image: cosmtrek/air
    container_name: takehome_server
    working_dir: /app/cmd/server
    environment:
      POSTGRES_DSN: postgresql://${DB_USER}:${DB_PASSWORD}@postgres_db:5432/${DB_NAME}
      DEV_LOGGING: ${DEV_LOGGING}
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./:/app/cmd/server
    depends_on:
      - postgres
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
