apiVersion: v1
kind: Service
metadata:
  name: takehome-api
  labels:
    app.kubernetes.io/app: takehome-api
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/app: takehome-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: api